### ISSUE TITLE
initGPIO() in weather.py no longer works with libgpiod library

### ISSUE THREAD

**Issue by llego** [kotamorishi/weather-impression#6]
Just a heads up: `weather.py` does not work with the the latest version of libgpiod. 

I installed the python3 libraries for gpiod by `apt install python3-libgpiod` as explained here https://stackoverflow.com/questions/74352978/python-libgpiod-vs-gpiod-packages-in-linux

I get this error:

```
Traceback (most recent call last):
  File "/home/xx/weather-impression/weather.py", line 536, in <module>
    update()
  File "/home/xx/weather-impression/weather.py", line 522, in update
    gpio_pin = initGPIO()
               ^^^^^^^^^^
  File "/home/xx/weather-impression/weather.py", line 509, in initGPIO
    config = gpiod.line_request()
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'gpiod' has no attribute 'line_request'
```

Another problem in `initGPIO()` is that `chip = gpiod.chip(0)` should be formatted like this when using the latest version of libgpiod: `chip = gpiod.Chip('0')`

I was able to resolve this by myself by commenting out the rows that use `initGPIO() `. The effect is essentially -- if I understand correctly -- that button presses don't work for me.

**Comment by kotamorishi** [comment]
Hi @llego

I guess you are using the 'python3-libgpiod' library, while this project uses the 'gpiod' library.

1. Which operating system and version are you using?
2. Have you try "sudo -H pip3 install gpiod"? Did the installation succeed?
3. Which "gpiod" version? It seems 1.5.4 is the latest.

**Comment by kotamorishi** [comment]
BTW I am not sure when I can but I will update this repo for the bookworm.

**Comment by llego** [comment]
**Which operating system and version are you using?** I'm using Bookworm on a rpi zero

**Have you try "sudo -H pip3 install gpiod"? Did the installation succeed?** I get this error. I'm not experienced in python development and managing python libraries, venv, etc., so I don't quite understand what's best practice in Bookworm vs. Bullseye... The error message below is the reason why I'm using `python3-libgpiod` instead of `gpiod` library.

```
xx@rpizero:~ $ sudo -H pip3 install gpiod
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Which "gpiod" version? It seems 1.5.4 is the latest.** 
```
xx@rpizero:~ $ sudo apt info python3-libgpiod
Package: python3-libgpiod
Version: 1.6.3-1+rpi1+b2

```

**Comment by kotamorishi** [comment]
I confirmed that Install script not working with **bookworm**. 
Python environment seems changed from Buster.

**Comment by llego** [comment]
By the way, thanks for this awesome project, I'm very happy with my implementation :) 

![PXL_20231014_054615663](https://github.com/kotamorishi/weather-impression/assets/8949656/f5ec9898-1b9f-4697-8cf4-25c1c4db22a1)

**Comment by kotamorishi** [comment]
fixed with https://github.com/kotamorishi/weather-impression/pull/9
